title: Internship case studies
description: Winternship 2025 solutions
theme: jekyll-theme-primer

exclude:
  - node_modules
  - "*/node_modules/*"
  - "*/tests/*"
  - "*.test.js"
  - dist
  - build
  - package.json
  - package-lock.json
  - yarn.lock
